HBRProject/Controllers/CategoryController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using DataAccesss.Interfaces;
using DataAccesss.InterfaceImplementations;
using DataAccesss.Models;
using System;

namespace HBRProject.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategories iCategories = new CategoriesImplementation();

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetAllCategories()
        {
            try
            {
                List<Categories> allCategories = iCategories.Retrieve();
                return Json(new { data = allCategories, success = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Error(e, false);
            }
        }

        [HttpPost]
        public JsonResult CreateCategory(Categories category)
        {
            try
            {
                iCategories.Create(category);
                return True();
            }
            catch (Exception e)
            {
                return Error(e, false);
            }
        }

        [HttpPost]
        public JsonResult UpdateCategory(Categories category)
        {
            try
            {
                iCategories.Update(category);
                return True();
            }
            catch (Exception e)
            {
                return Error(e, false);
            }
        }

        [HttpPost]
        public JsonResult DeleteCategory(Categories category)
        {
            try
            {
                iCategories.Delete(category);

                return True();
            }
            catch (Exception e)
            {
                return Error(e, false);
            }
        }

        public JsonResult True()
        {
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Error(Exception e, bool success)
        {
            return Json(new { errorMessage = e.Message.ToString(), success }, JsonRequestBehavior.AllowGet);
        }
    }
}

HBRProject/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccesss.Interfaces;
using DataAccesss.InterfaceImplementations;
using DataAccesss.Models;

namespace HBRProject.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProducts iProducts = new ProductsImplementation(); 

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetAllProducts()
        {
            try
            {
                List<Products> allProducts = iProducts.Retrieve();
                return Json(new { data = allProducts, success = true }, JsonRequestBehavior.AllowGet);
            }
            catch(Exception e)
            {
                return Error(e, false);
            }
        }

        [HttpPost]
        public JsonResult CreateProduct(Products product)
        {
            try
            {
                iProducts.Create(product);
                return True();
            }
            catch (Exception e)
            {
                return Error(e, false);
            }
        }

        [HttpPost]
        public JsonResult UpdateProduct(Products product)
        {
            try
            {
                iProducts.Update(product);
                return True();
            }
            catch (Exception e)
            {
                return Error(e, false);
            }
        }

        [HttpPost]
        public JsonResult DeleteProduct(Products product)
        {
            try
            {
                iProducts.Delete(product);
                return True();
            }
            catch (Exception e)
            {
                return Error(e, false);
            }

        }

        public JsonResult True()
        {
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Error(Exception e, bool success)
        {
            return Json(new { errorMessage = e.Message.ToString(), success }, JsonRequestBehavior.AllowGet);
        }
    }
}

HBRProject/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccesss.Interfaces;
using DataAccesss.InterfaceImplementations;
using DataAccesss.Models;

namespace HBRProject.Controllers
{
    public class UserController : Controller
    {
        private readonly IUsers iUsers = new UsersImplementation();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Registration()
        {
            return View();
        }

        public new ActionResult Profile()
        {
            return View();
        }

        [HttpPost]
        public JsonResult CreateUser(Users user)
        {
            try
            {
                iUsers.Create(user);
                return True();
            }
            catch(Exception e)
            {
                return Error(e, false);
            }
        }

        [HttpPost]
        public JsonResult GetUser(string username)
        {
            try
            {
                List<Users> userData = iUsers.GetUserList(username);
                return Json(new { data = userData, success = true }, JsonRequestBehavior.AllowGet);
            }
            catch(Exception e)
            {
                return Error(e, false);
            }
        }

        [HttpPost]
        public JsonResult Login(Users user)
        {
            try
            {
                if (iUsers.IsUserValid(user))
                {
                    return True();
                }
            }
            catch(Exception e)
            {
                return Error(e, false);
            }
            return Json(new { success = false }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult UpdateUser(Users user)
        {
            try
            {
                iUsers.Update(user);
                return True();
            }
            catch(Exception e)
            {
                return Error(e, false);
            }
        }

        public JsonResult True()
        {
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Error(Exception e, bool success)
        {
            return Json(new { errorMessage = e.Message.ToString(), success}, JsonRequestBehavior.AllowGet);
        }
    }
}

HBRProject/Views/Category/Index.cshtml
@{
    ViewBag.Title = "Categories";
}

<head>
    <script src="~/Scripts/authInterceptor.js"></script>
</head>

@*El datatable*@

<div>
    <h2>Categories</h2>
    <button type="button" id="btnCreate" class="btn btn-success">Create new</button>
    <br /><br />
    <table id="datatable" class="table table-bordered table-hover" style="width:100%;">
        <thead>
            <tr>
                <th>id</th>
                <th>Category name</th>
                <th>Action</th>
            </tr>
        </thead>
    </table>
</div>

@*Modal para crear nuevo.*@

<div id="categoryFormCreate" class="modal fade" style="transform: translateY(13%);" role="dialog" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4>Create a category</h4>
            </div>
            <div class="modal-body">
                <form id="createForm">
                    <div class="form-group">
                        <label>Category Name</label>
                        <input id="categoryCreate" name="categoryName" class="form-control" type="text" />
                    </div>
                    <div class="modal-footer">
                        <input type="submit" id="btnModalCreate" value="Create" class="btn btn-success" />
                        <button type="button" class="btn btn-outline-success" data-dismiss="modal">Close</button>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

@*Modal para editar/modificar.*@

<div id="categoryFormUpdate" class="modal fade" style="transform: translateY(13%);" role="dialog" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4>Edit a category</h4>
            </div>
            <div class="modal-body">
                <form id="updateForm">
                    <div class="form-group">
                        <label>Category Id</label>
                        <input id="idUpdate" class="form-control" type="text" readonly />
                    </div>
                    <div class="form-group">
                        <label>Category Name</label>
                        <input id="categoryUpdate" name="categoryName" class="form-control" type="text" />
                    </div>
                    <div class="modal-footer">
                        <input type="submit" id="btnUpdate" value="Edit" class="btn btn-info" />
                        <button type="button" class="btn btn-outline-success" data-dismiss="modal">Close</button>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

@*Modal para mostrar los detalles.*@

<div id="categoryDetails" class="modal fade" style="transform: translateY(13%);" role="dialog" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4>Category details</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <h5 id="labelName"></h5>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-success" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

<link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" />

@section Scripts {

    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.2/dist/jquery.validate.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>

    <script>
        $(document).ready(function () {

            IsNotLogged()

            ValidateCreateForm()
            $('#createForm').submit(function (event) {
                event.preventDefault()

                if ($(this).valid()) {
                    CreateCategory()
                }
            })

            ValidateUpdateForm()
            $('#updateForm').submit(function (event) {
                event.preventDefault()

                if ($(this).valid()) {
                    UpdateCategory()
                }
            })

            let buttons = `
            <button class='btn btn-info edit' id='btnEdit'>Edit</button>
            &nbsp;
            <button class='btn btn-warning details' id='btnDetails'>Details</button>
            &nbsp;
            <button class='btn btn-danger delete' id='btnDelete'> Delete</button>
            `

            let datatable = $('#datatable').DataTable({
                "ajax": {
                    "type": "GET",
                    "url": "@Url.Action("GetAllCategories", "Category")",
                    "datatype": "JSON",
                },
                "columns": [
                    { "data": "categoryId", "visible": false },
                    { "data": "categoryName" },
                    { "defaultContent": buttons }
                ]
            })

            DatatableCreateOnClick()

            DatatableEditOnClick(datatable)

            DatatableDetailsOnClick(datatable)

            DatatableDeleteOnClick(datatable)

        })

        const DatatableCreateOnClick = () => {
            $('#btnCreate').click(function () {
                $('#categoryFormCreate').modal()
            })
        }

        const DatatableEditOnClick = (datatable) => {
            datatable.on('click', '.edit', function () {
                let row = datatable.row($(this).parents('tr'))

                let categoryId = row.data()['categoryId']
                let categoryName = row.data()['categoryName']

                $(".modal-body #idUpdate").val(categoryId)
                $(".modal-body #categoryUpdate").val(categoryName)
                $("#categoryFormUpdate").modal()
            })
        }

        const DatatableDetailsOnClick = (datatable) => {
            datatable.on('click', '.details', function () {
                let row = datatable.row($(this).parents('tr'))

                let categoryId = row.data()['categoryId']
                let categoryName = row.data()['categoryName']

                $(".modal-body #labelId").text(`Category id: ${categoryId}`)
                $(".modal-body #labelName").text(`Category name: ${categoryName}`)
                $("#categoryDetails").modal()
            })
        }

        const DatatableDeleteOnClick = (datatable) => {
            datatable.on('click', '.delete', function () {
                let row = datatable.row($(this).parents('tr'))

                let id = row.data()['categoryId']

                DeleteCategory(id)
                row.remove()
                datatable.draw()
            })
        }

        const CreateCategory = () => {

            let categoryName = $('#categoryFormCreate #categoryCreate').val()

            let category = JSON.stringify({ 'categoryName': categoryName })

            $.ajax({
                contentType: 'application/json; charset=utf-8',
                type: 'POST',
                url: "@Url.Action("CreateCategory", "Category")",
                data: category,
                success: function (response) {
                    if (response.success) location.reload();
                    else swal(response.errorMessage)
                }
            })
        }

        const UpdateCategory = () => {

            let categoryId = $('#categoryFormUpdate #idUpdate').val()
            let categoryName = $('#categoryFormUpdate #categoryUpdate').val()

            let category = JSON.stringify({ 'categoryId': categoryId, 'categoryName': categoryName })

            $.ajax({
                contentType: 'application/json; charset=utf-8',
                type: 'POST',
                url: "@Url.Action("UpdateCategory", "Category")",
                data: category,
                success: function (response) {
                    if (response.success) location.reload()
                    else swal(response.errorMessage)
                }
            })
        }

        const DeleteCategory = (categoryId) => {

            let category = JSON.stringify({ 'categoryId': categoryId })

            $.ajax({
                contentType: 'application/json; charset=utf-8',
                type: 'POST',
                url: "@Url.Action("DeleteCategory", "Category")",
                data: category,
                success: function (response) {
                    if (!response.success) swal(response.errorMessage)
                }
            })
        }

        const ValidateCreateForm = () => {
            $('#createForm').validate({
                rules: {
                    categoryName: {
                        required: true
                    }
                },
                messages: {
                    categoryName: {
                        required: 'Please provide a product name.'
                    }
                }
            })
        }

        const ValidateUpdateForm = () => {
            $('#updateForm').validate({
                rules: {
                    categoryName: {
                        required: true
                    }
                },
                messages: {
                    categoryName: {
                        required: 'Please provide a product name.'
                    }
                }
            })
        }

    </script>

}

HBRProject/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

HBRProject/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

HBRProject/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

HBRProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="~/Scripts/Logout.js"></script>
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="@Url.Action("Index", "Product")">HBR Group</a></li>
                    <li>@Html.ActionLink("Products", "Index", "Product")</li>
                    <li>@Html.ActionLink("Categories", "Index", "Category")</li>
                    <li>@Html.ActionLink("Profile", "Profile", "User")</li>
                    <li onclick="logout()">@Html.ActionLink("Logout", "Index", "User")</li>
                 </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: true)

</body>
</html>

HBRProject/Views/User/Index.cshtml
@{ 
    Layout = null;
}

<head>
    <title>Login</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/animate.css" rel="stylesheet">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="~/Scripts/authInterceptor.js"></script>
</head>
<body class="white-bg">
    <div>
        <div class="middle-box text-center loginscreen animated fadeInDown">
            <div>
                <div>
                    <img src="~/Content/Imgs/logo.png">
                    <h2>Log in</h2>
                    <br />
                </div>
                <center>
                    <form id="loginForm">
                        <div class="form-group">
                            <label for="username">Username:</label>
                            <input type="text" id="username" name="username" class="form-control" style="width:15%"/>
                        </div>
                        <div class="form-group">
                            <label for="password">Password:</label>
                            <input type="password" id="password" name="password" class="form-control" style="width:15%"/>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Login" class="btn">
                        </div>
                    </form>
                </center>
                <div>
                    Don't have an account? @Html.ActionLink("Sign up", "Registration", "User")
                </div>
            </div>
        </div>
    </div>
</body>
     <script src="https://code.jquery.com/jquery-3.5.1.js"
        integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.2/dist/jquery.validate.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>

    <script>
        $(document).ready(function () {
            IsLogged()
            ValidateForm()

            $('#loginForm').submit(function (event) {
                event.preventDefault()

                if ($(this).valid()) {
                    Login()
                }
            })
        })

        const Login = () => {

            let userName = $('#username').val()
            let password = $('#password').val()

            let user = JSON.stringify({
                'userName': userName,
                'userPassword': password
            })


            $.ajax({
                contentType: 'application/json; charset=utf-8',
                type: 'POST',
                url: "@Url.Action("Login", "User")",
                data: user,
                datatype: 'JSON',
                success: function (response) {
                    if (response.success) {
                        localStorage.setItem('isLogged', 'true');
                        localStorage.setItem('username', userName)
                        location.href = "@Url.Action("Index", "Product")"; 
                    }
                    else swal("Incorrect username or password")
                }
            })
        }

        const ValidateForm = () => {
            $('#loginForm').validate({
                rules: {
                    username: {
                        required: true
                    },
                    password: {
                        required: true
                    }
                },
                messages: {
                    username: {
                        required: 'Please enter your username.'
                    },
                    password: {
                        required: 'Please enter your password.',
                        minlength: 'Your password must be at least 6 characters long.'
                    }
                }
            })
        }

    </script>

HBRProject/Views/User/Profile.cshtml
@{
    ViewBag.Title = "Profile";
}

<head>
    <script src="~/Scripts/authInterceptor.js"></script>
    <script src="~/Scripts/User.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" />
</head>

<h2>Profile</h2>
<div class="userInformation">
    <div class="form-group" hidden>
        <label id="userId"></label>
    </div>
    <div class="form-group">
        <label id="userName"></label>
    </div>
    <div class="form-group">
        <label id="userFirstName"></label>
    </div>
    <div class="form-group">
        <label id="userLastName"></label>
    </div>
    <div class="form-group">
        <label id="userEmail"></label>
    </div>
    <div class="form-group">
        <label id="userPassword"></label>
    </div>
    <div class="form-group">
        <button type="submit" id="btnShowModal" class="btn btn-info">Edit Profile</button>
    </div>
</div>

<div id="userFormUpdate" class="modal fade" style="transform: translateY(13%);" role="dialog" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4>Edit your profile</h4>
            </div>
            <div class="modal-body">
                <form id="updateProfile">
                    <div class="form-group">
                        <label id="userId">id</label>
                        <input id="userIdInput" class="form-control" type="text" readonly />
                    </div>
                    <div class="form-group">
                        <label id="userName">Username</label>
                        <input id="userNameInput" name="username" class="form-control" type="text" />
                    </div>
                    <div class="form-group">
                        <label id="userFirstName">First Name</label>
                        <input id="userFirstNameInput" name="firstname" class="form-control" type="text" />
                    </div>
                    <div class="form-group">
                        <label id="userLastName">Last Name</label>
                        <input id="userLastNameInput" name="lastname" class="form-control" type="text" />
                    </div>
                    <div class="form-group">
                        <label id="userEmail">Email</label>
                        <input id="userEmailInput" name="email" class="form-control" type="email" />
                    </div>
                    <div class="form-group">
                        <label id="userPassword">Password</label>
                        <input id="userPasswordInput" name="password" class="form-control" type="password" />
                    </div>
                    <div class="modal-footer">
                        <input type="submit" id="btnUpdate" value="Edit" class="btn btn-info" />
                        <button type="button" class="btn btn-outline-success" data-dismiss="modal">Close</button>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>


@section Scripts {

    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.2/dist/jquery.validate.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>

    <script>
        $(document).ready(async function () {
            let user = await GetUser()

            IsNotLogged()

            ValidateForm()
            $('#updateProfile').submit(function (event) {
                event.preventDefault()

                if ($(this).valid()) {
                    UpdateProfile()
                }
            })

            FillLabels(user)
            ShowEditModal(user)
        })

        const ShowEditModal = (user) => {
            $('#btnShowModal').click(function () {
                $('.modal-body #userIdInput').val(user.userId)
                $('.modal-body #userNameInput').val(user.userName)
                $('.modal-body #userFirstNameInput').val(user.userFirstName)
                $('.modal-body #userLastNameInput').val(user.userLastName)
                $('.modal-body #userEmailInput').val(user.userEmail)

                $('#userFormUpdate').modal()
            })
        }

        const FillLabels = (user) => {
            $('#userId').text(`id: ${user.userId}`)
            $('#userName').text(`Username: ${user.userName}`)
            $('#userFirstName').text(`First Name: ${user.userFirstName}`)
            $('#userLastName').text(`Last name: ${user.userLastName}`)
            $('#userEmail').text(`Email: ${user.userEmail}`)
            $('#userPassword').text('Password: ******')
        }

        const UpdateProfile = () => {
            let userId = $('.modal-body #userIdInput').val()
            let userName = $('.modal-body #userNameInput').val()
            let userFirstName = $('.modal-body #userFirstNameInput').val()
            let userLastName = $('.modal-body #userLastNameInput').val()
            let userEmail = $('.modal-body #userEmailInput').val()
            let userPassword = $('.modal-body #userPasswordInput').val()

            let user = JSON.stringify({
                'userId': userId,
                'userName': userName,
                'userFirstName': userFirstName,
                'userLastName': userLastName,
                'userEmail': userEmail,
                'userPassword': userPassword
            })

            $.ajax({
                contentType: 'application/json; charset=utf-8',
                type: 'POST',
                url: "@Url.Action("UpdateUser", "User")",
                data: user,
                success: function (response) {
                    if (response.success) location.reload()
                    else swal(response.errorMessage)
                },
                error: function () {
                    swal("Ha ocurrido un error.")
                }
            })
        }

        const ValidateForm = () => {
            $('#updateProfile').validate({
                rules: {
                    username: {
                        required: true,
                        minlength: 2
                    },
                    firstname: {
                        required: true,
                    },
                    lastname: {
                        required: true,
                    },
                    email: {
                        required: true
                    },
                    password: {
                        required: true,
                        minlength: 6
                    }
                },
                messages: {
                    username: {
                        required: 'Please provide an username.',
                        minlength: 'Your username must consist of at least 2 characters.'
                    },
                    firstname: {
                        required: 'Please provide your first name.'
                    },
                    lastname: {
                        required: 'Please provide your last name. '
                    },
                    email: {
                        required: 'Please provide an email.'
                    },
                    password: {
                        required: 'Please provide a password.',
                        minlength: 'Your password must be at least 6 characters long.'
                    }
                }
            })
        }

    </script>
}